version: '3.8'

services:
  db:
    image: postgres:12.9-alpine
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: devmaua
      POSTGRES_DB: Dev.Materias
  # mss_materias:
  #   build:
  #     context: .
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/app
