
# This is a basic workflow to help you get started with Actions

name: CD


on:
  workflow_dispatch:

jobs:
  
  deploy-to-aws:

    runs-on: ubuntu-latest
    outputs:
        registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - uses: actions/checkout@v2
      
      # setar python para 3.9
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9.6
      
      # configurar venv
      - name: Create Virtual Enviroment
        run: python -m venv venv
      - name: Install Dependencies
        run: |
          source venv/bin/activate; \
          pip install -r requirements.txt \
      
      - name: Get Root Directory
        id: root_directory
        run: echo "::set-output name=name::$(pwd)"
     # ROOT:  ${{ steps.root_directory.outputs.name }}
      
      - name: Zip the app
        run:  | 
          cp -R server.py venv/lib/python3.9/site-packages; \
          cd venv/lib/python3.9/site-packages; \
          zip -r function.zip *; 
          mv function.zip  ${{ steps.root_directory.outputs.name }}\
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1 # HARD CODED
    
      - name: Upload zip on S3 Bucket
        run: aws s3 cp function.zip s3://devmaua-lambda-functions/${{ github.event.repository.name }}/function.zip # HARD CODED      
      # Atualizar lambda
      - name: Update Lambda Source Code
        run: aws lambda update-function-code --function-name subjects --s3-bucket devmaua-lambda-functions --s3-key ${{ github.event.repository.name }}/function.zip
      
