name: CI

on:
  push:
  pull_request:
    branches: [ helpers ]
  
  workflow_dispatch:

jobs:
  testApp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Runs tests
      run: python -m pytest  tests --ignore=tests/external/dynamo
    - name: Create coverage report
      run: |
        python -m pytest  tests --ignore=tests/external/dynamo --cov=./
